INSERT INTO USER(EMAIL,PASSWORD) VALUES('debi@monamitech.com','maa');
INSERT INTO USER(EMAIL,PASSWORD) VALUES('pallavi@monamitech.com','maa123');          
INSERT INTO USER(EMAIL,PASSWORD) VALUES('jhuna@monamitech.com','maa12345');

INSERT INTO ORGANISATION(NAME,CODE) VALUES('DEBIPRASAD MISHRA','MI2005');
INSERT INTO ORGANISATION(NAME,CODE) VALUES('PALLAVI PARAMITA NAYAK','MI2006');          
INSERT INTO ORGANISATION(NAME,CODE) VALUES('JHUNARANI SAHOO','MI2007');

INSERT INTO ROLE(NAME,CODE) VALUES('USER CREATION','USER');
INSERT INTO ROLE(NAME,CODE) VALUES('FINANCE DEPARTMENT','FD');          
INSERT INTO ROLE(NAME,CODE) VALUES('AUDIT DEPARTMENT','AU');
