DROP TABLE IF EXISTS USER;


create table user
(USER_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50),
);

DROP TABLE IF EXISTS ORGANISATION;


CREATE TABLE ORGANISATION
(ID INT(8) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
CODE VARCHAR(100),
);
DROP TABLE IF EXISTS ROLE;


CREATE TABLE ROLE
(ID INT(8) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(40),
CODE VARCHAR(60),
);
